"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.figmaToFlutter = exports.figmaToHtmlTailwindCss = exports.figmaToStandardHtmlCss = exports.Greeter = void 0;
const Greeter = (name) => `Hello ${name}`;
exports.Greeter = Greeter;
const figmaToStandardHtmlCss = () => 'here is your html';
exports.figmaToStandardHtmlCss = figmaToStandardHtmlCss;
const figmaToHtmlTailwindCss = () => 'here is your html with tailwind css';
exports.figmaToHtmlTailwindCss = figmaToHtmlTailwindCss;
const figmaToFlutter = () => 'here is your flutter code';
exports.figmaToFlutter = figmaToFlutter;
